version: "3.9"

services:
  auth.db:
    image: postgres:16
    container_name: auth_postgres
    restart: always
    ports:
      - "5433:5432"     # хост:контейнер
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  auth.api:
    build:
      context: Auth
      dockerfile: Dockerfile
    container_name: auth_api
    depends_on:
      - auth.db
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__AuthDb: "Host=auth.db;Port=5432;Database=auth_db;Username=auth;Password=auth_pass"
  
  booking.db:
    image: postgres:16
    container_name: booking_postgres
    restart: always
    ports:
      - "5434:5432"     # хост:контейнер
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_DB: booking_db
    volumes:
      - booking_postgres_data:/var/lib/postgresql/data

  booking.api:
    build:
      context: Booking
      dockerfile: Dockerfile
    container_name: booking_api
    depends_on:
      - booking.db
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: http://+:5001
      ConnectionStrings__AuthDb: "Host=auth.db;Port=5432;Database=booking_db;Username=booking_user;Password=booking_pass"
volumes:
  auth_postgres_data:
  booking_postgres_data: